import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/app/globals.css'
import { CartProvider } from "@/context/CartContext";
import { getPublicItems } from "@/lib/getPublicItems";
import { CustomerProvider } from "@/context/CustomerContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function CustomerLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{branchSlug: string}>
}>) {

  const {branchSlug} = await params;

  const branch = await  getPublicItems(branchSlug) 


  console.log('page2', branchSlug, branch ) 
  return (
    <>
      <CustomerProvider branch={branch}>
          {children}
      </CustomerProvider>
        
    </>
  );
}
