import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/app/globals.css'
import { CartProvider } from "@/context/CartContext";
import { Space_Grotesk } from "next/font/google";

const spaceGrotesk = Space_Grotesk({
      variable: "--font-space-grotesk",
      subsets: ["latin"],
    });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function CustomerLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{branchSlug: string}>
}>) {


    
    

  return (
    <html lang="en">
      <body
         className={`${spaceGrotesk.variable} ${spaceGrotesk.className} antialiased bg-[#f9741613]`}
      >
          <CartProvider>
            {children}
          </CartProvider>
        
        
      </body>
    </html>
  );
}
